---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webfrontend-deployment"
  labels:
    app.kubernetes.io/name: "xprtz-publish-kubernetes-apphost"
    app.kubernetes.io/component: "webfrontend"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "xprtz-publish-kubernetes-apphost"
        app.kubernetes.io/component: "webfrontend"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.webfrontend.webfrontend_image }}"
          name: "webfrontend"
          envFrom:
            - configMapRef:
                name: "webfrontend-config"
            - secretRef:
                name: "webfrontend-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.webfrontend.port_http }}"
            - name: "https"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.webfrontend.port_https }}"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "xprtz-publish-kubernetes-apphost"
      app.kubernetes.io/component: "webfrontend"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
