---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "webfrontend-service"
  labels:
    app.kubernetes.io/name: "xprtz-publish-kubernetes-apphost"
    app.kubernetes.io/component: "webfrontend"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "xprtz-publish-kubernetes-apphost"
    app.kubernetes.io/component: "webfrontend"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: "{{ .Values.parameters.webfrontend.port_http }}"
      targetPort: "{{ .Values.parameters.webfrontend.port_http }}"
    - name: "https"
      protocol: "TCP"
      port: "{{ .Values.parameters.webfrontend.port_https }}"
      targetPort: "{{ .Values.parameters.webfrontend.port_https }}"
